### ISSUE TITLE
Multiple Copies of same default task

### ISSUE THREAD

**Issue by Skath3** [Supamiu/Lostark-helper#12]
I have created my roster but in checklist I am getting this:

![image](https://user-images.githubusercontent.com/105175855/167316435-3cab876f-8924-4b9e-86e8-2c410ea88324.png)

I have tried in 2 different browsers and it still looks the same

Thank you for your assistance

**Comment by Supamiu** [comment]
It looks like this happened on various corrupted accounts, due to an issue with tasks duplicating that happened a few releases in the past, can you give me your user ID please? Best is to DM me @Miu#1568 on Discord.

**Comment by Skath3** [comment]
Didn't work, but no worries, I was able to create a new account and there it seems to be working properly. Tnx again for your assistance

PS
Discord account was not found, so I was not able to DM you :)
