### ISSUE TITLE
Feature request: custom gold rules

### ISSUE THREAD

**Issue by SneakyKenny** [Supamiu/Lostark-helper#130]
Following the Brel gold nerfs, most people are going to run kayangel instead.
It could be useful to pick the raids to count in the gold planner tab.

**Comment by fayaine** [comment]
You can already do that by simply using the "Taking Gold" or not taking gold slider. For Brel to fully disappear just set a custom max ilvl that is below your roster.

**Comment by SneakyKenny** [comment]
That's clever, thanks for the answer.
