### ISSUE TITLE
Increase readability of rest bonus bars

### ISSUE THREAD

**Issue by RyanWilkie** [Supamiu/Lostark-helper#15]
At a glance rest bonus can be hard to figure out how many bars you have. Especially when the bonus does not create full bars: 30, 50, 70 etc. This issue gets worse as the screen width gets smaller.

Increasing the z-index of `.energy-bar .threshold` seems to make it much more clear:

![image](https://user-images.githubusercontent.com/14125303/168434064-9fe72e1e-6e7b-4e51-bb6d-cf319d918c1c.png)

Compared to without:

![image](https://user-images.githubusercontent.com/14125303/168434168-219c8400-16c6-41df-8fc0-94f9a43b1d1a.png)

**Comment by Supamiu** [comment]
Hi, that's a good idea, a PR would be welcome 😄

**Comment by CalebKester** [comment]
![image](https://user-images.githubusercontent.com/1319995/181918966-17030862-7a84-4eb9-9e9a-e03099406b48.png)
Did this break? it looks like the calculation for the width is off as well as the color is now missing.
