### ISSUE TITLE
Feature Request: More customizable task tracking

### ISSUE THREAD

**Issue by MatchaCrisp** [Supamiu/Lostark-helper#25]
Really awesome project!

I'm just wondering, if it is possible to  have certain character-bound tasks reset at a different rhythm than the others?

e.g. All my alts are on a lazy schedule, however I do go on all of them to contribute to the guild daily. Can the guild contribution task reset daily and not every 3 days? 

Thanks!

**Comment by rodrigokiller** [comment]
Hi @MatchaCrisp , if I am not mistake, this is currently possible.
You need to go to the Settings page.
![image](https://user-images.githubusercontent.com/1853922/180453303-a5aaea46-ebb6-4220-a16e-09201b86767b.png)
Check this image, you can turn the lazy mode of any daily task on / off.

**Comment by MatchaCrisp** [comment]
@rodrigokiller you are absolutely correct! My bad for not seeing this before opening this issue.
