### ISSUE TITLE
Calendar for ingame events

### ISSUE THREAD

**Issue by mjt91** [Supamiu/Lostark-helper#28]
Hi,

found your app through some redditor. Fell in love rigth away. I want to migrate my settings from BynnArk and working smooth so far.
Only thing missing is the calendar view to see the ingame events and todays adventure islands.
See attached. Any plans to add this to the app?

Cheers

![grafik](https://user-images.githubusercontent.com/16541426/179051786-7e8ca6ff-74c8-4f03-b7cb-1bcd30496e3d.png)

**Comment by Supamiu** [comment]
The main issue with this is maintaining the data source, we don't have any API for this and it means having to maintain the list by hand :/

**Comment by mjt91** [comment]
Yes thought so myself that this is the biggest pain point. I think of maybe building my own api for that matter. Might be a nice weekend project

**Comment by mjt91** [comment]
I realized this might be more difficult than I initially thought. Also the landscape is quite saturated with multiple sites likes lostarktimer.app, toki.gg and many iOS apps.

Feel free to close the issue.
