### ISSUE TITLE
Add input validation for item level field

### ISSUE THREAD

**Issue by AlterEchoes** [Supamiu/Lostark-helper#3]
Setting an empty value in item level field and clicking "add" returns the message: "Please input your Password!"
![image](https://user-images.githubusercontent.com/16253239/166642184-4715792e-9841-42b1-8501-aa9243660b8b.png)

Also, you can set negative or empty values for item level once you add a character:
![image](https://user-images.githubusercontent.com/16253239/166642364-27be44cd-24f9-4a4a-8144-051736bf223b.png)

**Comment by Supamiu** [comment]
Closed by https://github.com/Supamiu/Lostark-helper/commit/2e9d14d5d52e8353229eeb689fd9e08e8178d0a5
