### ISSUE TITLE
When adding two characters with the same name, changes are propagated

### ISSUE THREAD

**Issue by AlterEchoes** [Supamiu/Lostark-helper#4]
For example, modifying the item level for one character modifies the item level for the other character with the same name.
The same goes for tasks marked as completed
![image](https://user-images.githubusercontent.com/16253239/166643239-d746efc3-bea7-47e6-9498-851f0ea5c211.png)
![image](https://user-images.githubusercontent.com/16253239/166643284-387d078f-6d9c-4cd2-b592-efca961b8f81.png)

**Comment by Supamiu** [comment]
This is because the name is used as identifier in the app, since you can't have two characters with the same name in the game.

If they're on different regions, I suggest preffixing or suffixing them with the region name, like `fff [KR]`.
