### ISSUE TITLE
Roster edition bug

### ISSUE THREAD

**Issue by maximaLzdnb** [Supamiu/Lostark-helper#5]
Hey, thanks for the app! Really digging the simplified look. :)

I encountered an usability breaking bug, although most likely very easy to fix.

**How to reproduce**
1) Create multiple characters in "Roster" page. Class and ilvl don't matter, just put in whatever.
2) Edit any of those character's ilvl

**Expected**
The ilvl changing and saving.

**Actually happening**
ALL characters are edited at the same time, and they all become the intended edition's class and ilvl. I'm pretty sure this is some sort of model binding issue where all characters component share the same data on edit somehow.

Tested on Chrome latest and Firefox latest.

Thanks!

**Comment by Supamiu** [comment]
Hi, can you reproduce the bug after doing Ctrl + F5? It seems like it's fixed but some people are still getting cached JS bundles, making them load the unfixed version 😄

**Comment by maximaLzdnb** [comment]
Oh alright, that's gone. I figured since I tried in private navigation it would not allow any cache. Thank you!
