### ISSUE TITLE
Tasks showing for a character outside of ilvl range

### ISSUE THREAD

**Issue by RyanWilkie** [Supamiu/Lostark-helper#6]
Example 1: a 1400 character is added. We get the 2 Oreha's Well dungeons and Argos.

Example 2: 1400 & 340 characters are added. The 1400 character also gets checkboxes for the Ancient Elveria dungeons added for the 340 character. Which by default is for range 340->960

**Comment by Supamiu** [comment]
This should now be fixed :) closing for tracking purpose
