### ISSUE TITLE
Rest bonus is not updating with daily reset

### ISSUE THREAD

**Issue by brianhuangee** [Supamiu/Lostark-helper#8]
Hi, I've only used this tool for one day, but I noticed that even though daily character/roster tasks reset, rest bonus isn't incremented by 20 after skipping Graids/Chaos so I have to manually update in settings. Sorry if I'm misreporting. Thanks!

**Comment by Supamiu** [comment]
Closed by https://github.com/Supamiu/Lostark-helper/commit/f6e2d22a0e6fae984114979593a357dcf135d023
